# BINANCE => 0
# BYBIT => 1
# OKX => 2
# HYPERLIQUID => 3
# PARADEX => 4
# EXTENDED => 5
# DYDX_V4 => 6
exchange: 1

# Capitalization will be handled automatically.
# Ending (USDT, USD, USDC) MUST be spelled out.
# Example: "BTCUSDT", "SOLUSDT", "pepeusdc", "Xmrusd"
symbol: "SOLUSDT"

# PLAIN => 0
# A&S => 1
# STINKY => 2
strategy: 0

parameters:
  common:
    total_orders: 3             # Consider your rate limits!
    max_usd_position: 100       # Value in $ (USD)

  plain:
    # Feature params
    trades_tick_excitement_short_window: 50
    trades_tick_excitement_long_window: 200
    trades_time_excitement_short_window: 30.0
    trades_time_excitement_long_window: 120.0
    trades_excitement_buffer: 2.0
    orderbook_imbalance_window: 100
    orderbook_imbalance_depth_bps: 50

    # Quote generator params
    minimum_spread: 10          # Value in BPS (Basis Points)
    aggressiveness: 0.75        # Must be 0.0 <-> 1.0
    taker_skew_threshold: 0.5   # Strategy will take when abs(fair_skew) exceeds this
  
  stinky:
    minimum_spread_bps: 50          # Value in BPS (Basis Points)
    maximum_spread_bps: 250         # Value in BPS (Basis Points)
    large_fill_threshold_usd: 100   # Threshold in USD for considering a fill as large